project/app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.MonthCalendar.as_view(), name='month'),
    path('month/<int:year>/<int:month>/', views.MonthCalendar.as_view(), name='month'),
    path('week/', views.WeekCalendar.as_view(), name='week'),
    path('week/<int:year>/<int:month>/<int:day>/', views.WeekCalendar.as_view(), name='week'),
    path('week_with_schedule/', views.WeekWithScheduleCalendar.as_view(), name='week_with_schedule'),
    path(
        'week_with_schedule/<int:year>/<int:month>/<int:day>/',
        views.WeekWithScheduleCalendar.as_view(),
        name='week_with_schedule'
    ),

    path(
        'month_with_schedule/',
        views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'
    ),
    path(
        'month_with_schedule/<int:year>/<int:month>/',
        views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'
    ),

    path('mycalendar/', views.MyCalendar.as_view(), name='mycalendar'),
    path(
        'mycalendar/<int:year>/<int:month>/<int:day>/', views.MyCalendar.as_view(), name='mycalendar'
    ),

    path(
        'month_with_forms/',
        views.MonthWithFormsCalendar.as_view(), name='month_with_forms'
    ),
    path(
        'month_with_forms/<int:year>/<int:month>/',
        views.MonthWithFormsCalendar.as_view(), name='month_with_forms'
    ),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]

project/app/models.py
import datetime
from django.db import models
from django.utils import timezone


class Schedule(models.Model):
    """スケジュール"""
    summary = models.CharField('概要', max_length=50)
    description = models.TextField('詳細な説明', blank=True)
    start_time = models.TimeField('開始時間', default=datetime.time(7, 0, 0))
    end_time = models.TimeField('終了時間', default=datetime.time(7, 0, 0))
    date = models.DateField('日付')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.summary


project/app/forms.py
from django import forms
from .models import Schedule


class BS4ScheduleForm(forms.ModelForm):
    """Bootstrapに対応するためのModelForm"""

    class Meta:
        model = Schedule
        fields = ('summary', 'description', 'start_time', 'end_time')
        widgets = {
            'summary': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
            }),
            'start_time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'end_time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
        }

    def clean_end_time(self):
        start_time = self.cleaned_data['start_time']
        end_time = self.cleaned_data['end_time']
        if end_time <= start_time:
            raise forms.ValidationError(
                '終了時間は、開始時間よりも後にしてください'
            )
        return end_time


class SimpleScheduleForm(forms.ModelForm):
    """シンプルなスケジュール登録用フォーム"""

    class Meta:
        model = Schedule
        fields = ('summary', 'date',)
        widgets = {
            'summary': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'date': forms.HiddenInput,
        }

project/app/views.py
from django.views import generic
from . import mixins


class MonthCalendar(mixins.MonthCalendarMixin, generic.TemplateView):
    """月間カレンダーを表示するビュー"""
    template_name = 'app/month.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        return context


class WeekCalendar(mixins.WeekCalendarMixin, generic.TemplateView):
    """週間カレンダーを表示するビュー"""
    template_name = 'app/week.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_week_calendar()
        context.update(calendar_context)
        return context


from .models import Schedule
...
...
class WeekWithScheduleCalendar(mixins.WeekWithScheduleMixin, generic.TemplateView):
    """スケジュール付きの週間カレンダーを表示するビュー"""
    template_name = 'app/week_with_schedule.html'
    model = Schedule
    date_field = 'date'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_week_calendar()
        context.update(calendar_context)
        return context


class MonthWithScheduleCalendar(mixins.MonthWithScheduleMixin, generic.TemplateView):
    """スケジュール付きの月間カレンダーを表示するビュー"""
    template_name = 'app/month_with_schedule.html'
    model = Schedule
    date_field = 'date'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        return context


import datetime
from django.shortcuts import redirect
from django.views import generic
from . import mixins
from .forms import BS4ScheduleForm
from .models import Schedule
...
...

class MyCalendar(mixins.MonthCalendarMixin, mixins.WeekWithScheduleMixin, generic.CreateView):
    """月間カレンダー、週間カレンダー、スケジュール登録画面のある欲張りビュー"""
    template_name = 'app/mycalendar.html'
    model = Schedule
    date_field = 'date'
    form_class = BS4ScheduleForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        week_calendar_context = self.get_week_calendar()
        month_calendar_context = self.get_month_calendar()
        context.update(week_calendar_context)
        context.update(month_calendar_context)
        return context

    def form_valid(self, form):
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        if month and year and day:
            date = datetime.date(year=int(year), month=int(month), day=int(day))
        else:
            date = datetime.date.today()
        schedule = form.save(commit=False)
        schedule.date = date
        schedule.save()
        return redirect('app:mycalendar', year=date.year, month=date.month, day=date.day)


import datetime
from django.shortcuts import redirect, render
from django.views import generic
from .forms import BS4ScheduleForm, SimpleScheduleForm
from .models import Schedule
from . import mixins
...
...
class MonthWithFormsCalendar(mixins.MonthWithFormsMixin, generic.View):
    """フォーム付きの月間カレンダーを表示するビュー"""
    template_name = 'app/month_with_forms.html'
    model = Schedule
    date_field = 'date'
    form_class = SimpleScheduleForm

    def get(self, request, **kwargs):
        context = self.get_month_calendar()
        return render(request, self.template_name, context)

    def post(self, request, **kwargs):
        context = self.get_month_calendar()
        formset = context['month_formset']
        if formset.is_valid():
            formset.save()
            return redirect('app:month_with_forms')

        return render(request, self.template_name, context)




project/app/templates/app/base.html
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>カレンダー</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app:month' %}">月間カレンダー</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app:week' %}">週間カレンダー</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app:month_with_schedule' %}">スケジュール付き月間カレンダー</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app:week_with_schedule' %}">スケジュール付き週間カレンダー</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app:mycalendar' %}">登録機能付き月間・週間カレンダー</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app:month_with_forms' %}">一括登録付き月間カレンダー</a>
      </li>
    </ul>
  </div>
</nav>

<div class="container mt-3">
    {% block content %}{% endblock %}
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
{% block extrajs %}{% endblock %}
</body>
</html>

project/app/templates/app/includes/month.html
<a href="{% url 'app:mycalendar' month_previous.year month_previous.month month_previous.day %}">前月</a>
{{ month_current | date:"Y年m月" }}
<a href="{% url 'app:mycalendar' month_next.year month_next.month month_next.day %}">次月</a>

<table class="table" style="table-layout: fixed;">
    <thead>
    <tr>
        {% for w in week_names %}
            <th>{{ w }}</th>
        {% endfor %}
    </tr>
    </thead>
    <tbody>
    {% for week in month_days %}
        <tr>
            {% for day in week %}
                {% if now == day %}
                    <td class="table-success">
                {% else %}
                    <td>
                {% endif %}

                <a href="{% url 'app:mycalendar' day.year day.month day.day %}">{{ day.day }}</a>
                </td>
            {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
</table>

project/app/templates/app/includes/week.html
<a href="{% url 'app:mycalendar' week_previous.year week_previous.month  week_previous.day %}">前週</a>
{{ week_first | date:"Y年m月d日" }}〜{{ week_last | date:"Y年m月d日" }}
<a href="{% url 'app:mycalendar' week_next.year week_next.month  week_next.day %}">次週</a>

<table class="table" style="table-layout: fixed;">
    <tbody>
    <tr>
        {% for day in week_days %}
            {% if now == day %}
                <td class="table-success">
                    {% else %}
                <td>
            {% endif %}
        {% if week_first.month != day.month %}
            {{ day | date:"m/d" }}
        {% else %}
            {{ day.day }}
        {% endif %}
        </td>
        {% endfor %}
    </tr>
    <tr>
        {% for schedules in week_day_schedules.values %}
            <td>
                {% for s in schedules %}
                    {{ s.start_time }} - {{ s.end_time }}<br>
                    {{ s.summary }}<br>
                    {{ s.description | linebreaks }}
                {% endfor %}
            </td>
        {% endfor %}
    </tr>
    </tbody>
</table>

project/app/templates/app/month.html
{% extends 'app/base.html' %}

{% block content %}
    <a href="{% url 'app:month' month_previous.year month_previous.month %}">前月</a>
    {{ month_current | date:"Y年m月" }}
    <a href="{% url 'app:month' month_next.year month_next.month %}">次月</a>

    <table class="table">
        <tbody>
        {% for week in month_days %}
            <tr>
                {% for day in week %}
                    {% if now == day %}
                        <td class="table-success">
                            {% else %}
                        <td>
                    {% endif %}

                {% if month_current.month != day.month %}
                    {{ day | date:"m/d" }}
                {% else %}
                    {{ day.day }}
                {% endif %}

                </td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

project/app/templates/app/month_with_forms.html
{% extends 'app/base.html' %}
{% block content %}
    <style>
        table {
            table-layout: fixed;
        }

    </style>

    <a href="{% url 'app:month_with_forms' month_previous.year month_previous.month %}">前月</a>
    {{ month_current | date:"Y年m月" }}
    <a href="{% url 'app:month_with_forms' month_next.year month_next.month %}">次月</a>

    <form action="" method="POST">
        {{ month_formset.management_form }}
        <table class="table">
            <thead>
            <tr>
                {% for w in week_names %}
                    <th>{{ w }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for week_day_forms in month_day_forms %}
                <tr>
                    {% for day, forms in week_day_forms.items %}
                        {% if now == day %}
                            <td class="table-success">
                                {% else %}
                            <td>
                        {% endif %}

                    <div>
                        {% if month_current.month != day.month %}
                            {{ day | date:"m/d" }}
                        {% else %}
                            {{ day.day }}
                        {% endif %}

                        {% for form in forms %}
                            {{ form.as_p }}
                        {% endfor %}
                    </div>
                    </td>
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">送信</button>
    </form>
{% endblock %}

project/app/templates/app/month_with_schedule.html
{% extends 'app/base.html' %}
{% block content %}
    <style>
        table {
            table-layout: fixed;
        }

        td > div {
            height: 100px;
            overflow: hidden;
            white-space: nowrap;
        }

    </style>
    <a href="{% url 'app:month_with_schedule' month_previous.year month_previous.month %}">前月</a>
    {{ month_current | date:"Y年m月" }}
    <a href="{% url 'app:month_with_schedule' month_next.year month_next.month %}">次月</a>

    <table class="table">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for week_day_schedles in month_day_schedules %}
            <tr>
                {% for day, schedules in week_day_schedles.items %}
                    {% if now == day %}
                        <td class="table-success">
                            {% else %}
                        <td>
                    {% endif %}

                <div>
                    {% if month_current.month != day.month %}
                        {{ day | date:"m/d" }}
                    {% else %}
                        {{ day.day }}
                    {% endif %}

                    {% for schedule in schedules %}
                        <p>{{ schedule.summary }}</p>
                    {% endfor %}
                </div>
                </td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

project/app/templates/app/mycalendar.html
{% extends 'app/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-3">
            {% include 'app/includes/month.html' %}
            <hr>
            <form action="" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}"
                               class="col-sm-4 col-form-label">{{ field.label_tag }}</label>
                        <div class="col-sm-8">
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary btn-block">送信</button>
            </form>
        </div>
        <div class="col-md-9">
            {% include 'app/includes/week.html' %}
        </div>
    </div>
{% endblock %}


{% block extrajs %}
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
    <script>
        $(function () {
            // timedropper
            $("#id_start_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
            $("#id_end_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
        });
    </script>
{% endblock %}

project/app/templates/app/week.html
{% extends 'app/base.html' %}
{% block content %}

    <a href="{% url 'app:week' week_previous.year week_previous.month  week_previous.day %}">前週</a>
    {{ week_first | date:"Y年m月d日" }}〜{{ week_last | date:"Y年m月d日" }}
    <a href="{% url 'app:week' week_next.year week_next.month  week_next.day %}">次週</a>

    <table class="table">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        <tr>
            {% for day in week_days %}
                {% if now == day %}
                    <td class="table-success">
                        {% else %}
                    <td>
                {% endif %}
            {% if week_first.month != day.month %}
                {{ day | date:"m/d" }}
            {% else %}
                {{ day.day }}
            {% endif %}
            </td>
            {% endfor %}
        </tr>
        </tbody>
    </table>
{% endblock %}

project/app/templates/app/week_with_schedule.html
{% extends 'app/base.html' %}
{% block content %}

    <a href="{% url 'app:week_with_schedule' week_previous.year week_previous.month  week_previous.day %}">前週</a>
    {{ week_first | date:"Y年m月d日" }}〜{{ week_last | date:"Y年m月d日" }}
    <a href="{% url 'app:week_with_schedule' week_next.year week_next.month  week_next.day %}">次週</a>

    <table class="table table-bordered">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        <tr>
            {% for day in week_days %}
                {% if now == day %}
                    <td class="table-success">
                {% else %}
                    <td>
                {% endif %}
            {% if week_first.month != day.month %}
                {{ day | date:"m/d" }}
            {% else %}
                {{ day.day }}
            {% endif %}
            </td>
            {% endfor %}
        </tr>
        <tr>
            {% for schedules in week_day_schedules.values %}
                <td>
                    {% for s in schedules %}
                        {{ s.start_time }} - {{ s.end_time }}<br>
                        {{ s.summary }}<br>
                        {{ s.description | linebreaks }}
                    {% endfor %}
                </td>
            {% endfor %}
        </tr>
        </tbody>
    </table>
{% endblock %}